// Generated by ReScript, PLEASE EDIT WITH CARE


var body = document.querySelector("body");

if (!(body == null)) {
  var p = document.createElement("p");
  p.innerText = "...world!";
  body.appendChild(p);
}

export {
  
}
/* body Not a pure module */
