// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Webapi__Dom__Element from "rescript-webapi/src/Webapi/Dom/Webapi__Dom__Element.res.mjs";
import * as Webapi__Dom__HtmlSelectElement from "rescript-webapi/src/Webapi/Dom/Webapi__Dom__HtmlSelectElement.res.mjs";

var gameModeSelect = Belt_Option.getExn(Caml_option.nullable_to_opt(document.getElementById("game-mode")));

var agentDifficultyContainer = Belt_Option.getExn(Caml_option.nullable_to_opt(document.getElementById("agent-difficulty-container")));

gameModeSelect.addEventListener("change", (function (param) {
        var gameMode = Belt_Option.getExn(Webapi__Dom__HtmlSelectElement.ofElement(gameModeSelect));
        var gameMode$1 = gameMode.value;
        var diffStyle = Belt_Option.getExn(Webapi__Dom__Element.asHtmlElement(agentDifficultyContainer)).style;
        switch (gameMode$1) {
          case "player-vs-agent" :
              diffStyle.setProperty("display", "block", "");
              return ;
          case "player-vs-player" :
              diffStyle.setProperty("display", "none", "");
              return ;
          default:
            return ;
        }
      }));

export {
  gameModeSelect ,
  agentDifficultyContainer ,
}
/* gameModeSelect Not a pure module */
